### ISSUE TITLE
How can I use 3d object loaders like GLTF Loader or FBX Loader to load 3d objects?

### ISSUE THREAD

**Issue by umar-shafiq** [angular-threejs/angular-three#13]
How can I use 3d object loaders like GLTF Loader or FBX Loader to load 3d objects with a loading manager in angular three?

**Comment by umar-shafiq** [comment]
I am working on a character customizer. I have an example code in THREE js in Angular Component, I wanted to port it to Angular-Three. What I was is doing that I am adding or removing meshes from a character 3d model to make it appear different. for example, I have a character with no clothes. I can add clothes and remove clothes from the character's body by adding or removing meshes from the main model. Can you help me understand how can I achieve this in angular Three, I can share the reference code as well in three js.

**Comment by nartc** [comment]
Yeah, feel free to share your vanilla THREE.js code.
