### ISSUE TITLE
[documentation] How to use GridHelper、Gizmohelper and TransformControls?

### ISSUE THREAD

**Issue by yywf77** [angular-threejs/angular-three#15]
How to use GridHelper、Gizmohelper and TransformControls?

**Comment by nartc** [comment]
- `GridHelper` should be supported out of the box with `extend({ GridHelper })` or `extend(THREE)`
- `TransformControls` can be supported with importing `TransformControls` from `three/examples` or `three-stdlib`; then `extend({ TransformControls })`. I'd recommend importing it from `three-stdlib`
  - This might come from `angular-three-soba` in the near future.

For `GizmoHelper`, you could technically use `extend()` for a 3rd-party `GizmoHelper` class that is compatible with THREE.js
