### ISSUE TITLE
Issues migrating from @angular-three to angular-three

### ISSUE THREAD

**Issue by IRobot1** [angular-threejs/angular-three#21]
Missing with no obvious replacement
NgtTriple - 
```js 
position = [0, 0, 0] as NgtTriple`
```
Radian Pipe - 
```js
item.rotation | radian
```
Ready Event - 
```js
(ready)="meshready($event)"
```
Value of local variable -instance is no 
```js
<ngt-mesh #inst (click)="click(inst.instance.value)" >
```

No documentation for 
NgtLoader
```js
  constructor(private loader: NgtLoader) { }
    const s = this.loader.use(TextureLoader, newvalue).subscribe(next => {
      this.texture = next;
    },
      () => { },
      () => { s.unsubscribe(); }
    );
```

**Comment by IRobot1** [comment]
```js
<ngt-color attach="background" color="gray"></ngt-color>
```
migrates to
```js
<ngt-color attach="background" *args="['gray']"></ngt-color>
```

**Comment by IRobot1** [comment]
I used to be able to do this
```html
<ngt-mesh #inst (click)="this.panelSelected.next(inst.instance.value)">
```

Looks like inst variable is now an NgtMesh which is extends Mesh.  I can't do this, because I get a compile error
TS2345: Argument of type 'NgtMesh' is not assignable to parameter of type 'Object3D<Event>'.
```html
<ngt-mesh #inst (click)="this.panelSelected.next(inst)">
```

Also, I can't do this either, due to a different compile error
```html
<ngt-mesh #inst (click)="this.panelSelected.next(<Object3D><unknown>inst)">
```

I'm forced to create a function just to handle the type conversion
```html
<ngt-mesh #inst (click)="doclick(inst)">
```
```js
@Output() panelSelected = new EventEmitter<Object3D>();
doclick(mesh: NgtMesh) {
  this.panelSelected.emit(<Object3D><unknown>mesh)
}
```

Is there a better way to handle this?

**Comment by nartc** [comment]
Unfortunately, `NgtMesh` is an expended type of `Mesh` and it is required to have the custom renderer working with property like `[position]` and such. What you can do is to cast as `$any()` on the template. The type of the EventEmitter doesn't have to change.
