### ISSUE TITLE
Update main branch to support V17 while angular-three 2.0 is still cooking

### ISSUE THREAD

**Issue by MitchSmoot** [angular-threejs/angular-three#30]
I need this library to be updated to support angular 17 ASAP, for a current project of mine.

I am willing to work on this issue myself and submit a PR once I can get this compatible with V17.
Perhaps I'm biting off more than I can chew, maybe there is a very good reason V17 is being delayed for the 2.0 release, but I'm sure I'll learn a lot by trying.

Chau, let me know if this is a bad idea. if 2.0 is close by, or if you would prefer I instead help you on the 2.0 branch, I would be happy to defer to your judgement

**Comment by Oznerologos** [comment]
Hi there, any news about this ? I recently decided to try angular17 and wanted to have fun with 3D stuff and i still can't install angular-three (i'd rather not switch back to angular16 and relearn stuff i had to forget first ahah)

**Comment by nartc** [comment]
Apologize for the delayed response. I was off from angular-three for quite some time and only recently got back to it to push v2 over the finish line.

However, change detection with Signals have changed during this in Angular 18 release and that allows me to drop all the CD handling in the Angular Three event system so I've decided to make the requirement for v2 to be v18+. That said, v17 is _technically_ usable but events won't _automatically_ update the template even if Signals are used on the template.

With this in mind, I'll be closing this issue as v2 is coming really really soon (hopefully this weekend).

Once again, sorry for the delayed response.
