### ISSUE TITLE
 Cannot read properties of null (reading '__ngt_renderer__')

### ISSUE THREAD

**Issue by RyannGalea** [angular-threejs/angular-three#40]
Hi Chau,

I'm on:
```
    "angular-three": "^2.0.0-beta.289",
    "angular-three-postprocessing": "^2.0.0-beta.289",
    "angular-three-soba": "^2.0.0-beta.289",
```

Having an issue where it seems once *args data is updated the template tries to load the new information I get:
![image](https://github.com/user-attachments/assets/0ff0b7f8-edf1-4ea8-b88a-5af500171c7b)

![image](https://github.com/user-attachments/assets/d8931c7b-4ff5-471e-a7e6-a02964f887a0)

This all worked on earlier versions I believe but my cache may have been messed up for a few updates. Any idea to what would cause this?

Edit:
I actually have no idea when this happens but I cant even get the scene to load now. very confusing.]

**Comment by elkestudio** [comment]
What is your Angular version?

**Comment by RyannGalea** [comment]
I don't have the code right now but @latest basically.

**Comment by RyannGalea** [comment]
```
    "@angular/animations": "^18.1.4",
    "@angular/common": "^18.1.4",
    "@angular/compiler": "^18.1.4",
    "@angular/core": "^18.1.4",
    "@angular/forms": "^18.1.4",
    "@angular/platform-browser": "^18.1.4",
    "@angular/platform-browser-dynamic": "^18.1.4",
    "@angular/router": "^18.1.4",
```

**Comment by RyannGalea** [comment]
I just reverted back to a branch from 7 days  ago and it's still erroring out. So I don't even know how its been working I'm guessing from old cache.

```
    "@angular/animations": "^18.1.3",
    "@angular/common": "^18.1.3",
    "@angular/compiler": "^18.1.3",
    "@angular/core": "^18.1.3",
    "@angular/forms": "^18.1.3",
    "@angular/platform-browser": "^18.1.3",
    "@angular/platform-browser-dynamic": "^18.1.3",
    "@angular/router": "^18.1.3",

    "angular-three": "^2.0.0-beta.253",
    "angular-three-soba": "^2.0.0-beta.253",
```

**Comment by RyannGalea** [comment]
I have been able to re-create the issue in a small repo, it adds a geometry then after a 5 second delay tries to change the geometry and sends an error to the console.

https://github.com/RyannGalea/a3-repo

**Comment by RyannGalea** [comment]
Stackblitz:

https://stackblitz.com/~/github.com/RyannGalea/a3-repo

**Comment by nartc** [comment]
This is due to a recent change in Angular core (https://github.com/angular/angular/pull/57203). beta.302 has been released. Can you give that a try?

**Comment by nartc** [comment]
@RyannGalea Glad that it works again for you now. The problem is Angular core does not provide the `parent` anymore when calling `removeChild` (this gets invoked when a piece of the template goes into unmount phase, aka when a structural directive changes). Angular Three Renderer previously relied on having both `parent` and `oldChild` there to function. Recent fix removes this reliant.

**Comment by RyannGalea** [comment]
Angular 18.2.0 brings back this issue slightly different. 

![image](https://github.com/user-attachments/assets/afc7f7e5-a93c-4ccf-bd69-faf040dfeb90)

**Comment by nartc** [comment]
I'll take a quick look. I haven't tested against 18.2 yet.

**Comment by nartc** [comment]
@RyannGalea beta.308 is released. This was actually my fault, I forgot to call a signal 🫠

**Comment by RyannGalea** [comment]
Working again :)
