### ISSUE TITLE
[soba] add gizmo helper

### ISSUE THREAD

**Issue by nartc** [angular-threejs/angular-three#53]

**Comment by yywf77** [comment]
Hi nartc,TransformControls is a very useful tool, it would be even better if it could be added

**Comment by nartc** [comment]
@yywf77 `TransformControls` will come. In the mean time, do you find `PivotControls` (https://soba.angularthree.org/?path=/story/controls-pivotcontrols--default) suitable for your needs?

**Comment by yywf77** [comment]
@nartc My project is still based on version 1.10.7, and I have been studying the changes related to v2 these days. It may be a bit troublesome to transfer it, but if I wait until the aforementioned things are added before transferring, it may save a lot of unnecessary trouble. I will learn more about PivotControls later, thank you very much!

**Comment by nartc** [comment]
Got it.

**Comment by nartc** [comment]
@yywf77 both `TransformControls` and `GizmoHelper` are released in 2.2.0 

Please check the Storybook for usage information while documentation is being worked on.

**Comment by yywf77** [comment]
@nartc Thank you!
