### ISSUE TITLE
About NgtgizmoHelper

### ISSUE THREAD

**Issue by yywf77** [angular-threejs/angular-three#56]
Hi nartc! As shown below, this will prompt an error when used, but it can still run.

const defaultViewcubeOptions:NgtsGizmoViewcubeOptions = {
	font: "3.2rem Inter var, Arial, sans-serif",
	opacity: 1,
	color: '#00c8d6',
	hoverColor: '#00b0bd',
	textColor: 'black',
	strokeColor: '#00b0bd',
    faces: ['右', '左', '上', '下', '前', '后'],
};

  viewcubeOptions  = input(defaultViewcubeOptions as Partial<NgtsGizmoViewcubeOptions>);

Error message：

导出类的公共属性“viewcubeOptions”具有或正在使用外部模块“"/Users/adminstrator/workspace/new/smart-mine/sm-admin/node_modules/angular-three-soba/gizmos/lib/gizmo-helper/gizmo-viewcube"”中的名称“CommonOptions”，但不能为其命名
(property) GizmoHelper.viewcubeOptions: InputSignal<Partial<Partial<CommonOptions>>>

**Comment by nartc** [comment]
Hi @yywf77 

I'm not entirely sure of the fix but 2.3.1 has been released to also export the internal `CommonOptions` type. Can you try it out to see if the error's gone?

**Comment by yywf77** [comment]
Hi nartc 

The issue above has been resolved，thank you!   Another issue is that adding a light source has no effect. What's going on？
