### ISSUE TITLE
Custom SVG Renderer

### ISSUE THREAD

**Issue by reyryan** [angular-threejs/angular-three#57]
Hi,

Is there a way to use SVGRenderer inside Angular Three ?
I have a requirement where I need to use the LineBasicMaterial with its linewidth property set to >1.

Basically, it should work like this one in the official ThreeJS example.
https://threejs.org/examples/?q=line#svg_lines

Any guide on this please.

Than you.

**Comment by nartc** [comment]
Hi,

Please check the example here: https://github.com/angular-threejs/angular-three/blob/main/apps/kitchen-sink/src/app/misc/svg-renderer/svg-renderer.ts

Demo: https://demo.angularthree.org/misc/svg-renderer ported from the ThreeJS SVG Lines example.

Let me know if you have further questions.

**Comment by reyryan** [comment]
Hello nartc,

Thanks a lot for your quick response. I tried the code that you linked above, however I hit a 'gl.setClearAlpha is not a function' error when running it.

```
main.ts:5 ERROR TypeError: gl.setClearAlpha is not a function
    at Object.configure (angular-three.mjs:2401:14)
    at _NgtCanvas.noZoneResizeEffect (angular-three.mjs:2590:25)
    at effect.injector [as effectFn] (angular-three.mjs:2574:16)
    at EffectHandle.runEffect (core.mjs:37277:12)
    at Object.fn (core.mjs:37272:52)
    at Object.run (signals.mjs:507:12)
    at EffectHandle.run (core.mjs:37288:18)
    at ZoneAwareEffectScheduler.flushQueue (core.mjs:37255:14)
    at core.mjs:37245:31
    at _ZoneDelegate.invoke (zone.js:369:28)
```

I'm not really sure what did I do wrong. I just cloned your threejs template and added svgRendererFactory as you suggested.

```
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <ngt-canvas [sceneGraph]="sceneGraph"  [gl]="svgRendererFactory" />
  `,
  host: { class: 'block h-dvh w-full' },
  imports: [NgtCanvas],
})
export class AppComponent {
  sceneGraph = Experience;

  svgRendererFactory = (canvas: NgtCanvasElement) => {
		const renderer = new SVGRenderer();

		if (canvas instanceof HTMLCanvasElement) {
			canvas.style.display = 'none';
			canvas.parentElement?.appendChild(renderer.domElement);
		}

		return renderer;
	};
}
```

**Comment by nartc** [comment]
ah I did changed something internal. Lemme cut a patch release

**Comment by nartc** [comment]
Give 2.3.2 a try

**Comment by reyryan** [comment]
Hello nartc,

I ended up extending the existing SVGRenderer and creating an empty function for "setClearAlpha" instead since I have difficulty installing the patch version.

Thank you so much for this great library by the way. This opens a lot of avenues in the Angular community.

**Comment by nartc** [comment]
@reyryan can you open a new issue on what problems you ran into trying to instal the patch version? 

Extending the SVGRenderer is a nice workaround! I'll close this issue.
