### ISSUE TITLE
No release satisfies Angular 17

### ISSUE THREAD

**Issue by AadamZ5** [angular-threejs/angular-three#59]
I can't find a tagged release that satisfies Angular 17. My project is currently stuck at 17 for some other reasons we can't address right now. While trying to evaluate this library for our usage, NPM couldn't resolve a compatible package. I thought NPM was being... NPM, so I looked into it and it seems like there is actually no suitable release for Angular 17.

I notice a jump from Angular 16 in [`2.0.0-beta.42`](https://github.com/angular-threejs/angular-three/blob/5f6361e19296bba1d5b04be70bf1bc5e21177ecd/package.json#L95-L105) to Angular 18 in [`2.0.0-beta.279`](https://github.com/angular-threejs/angular-three/blob/b13ef258350ce89a79ed50e30d03d42f8074f15b/package.json#L109-L117).

I can't say I'm stuck here and needing this library, but it seems like it could be an issue for others at some point. Not sure if there's an easy retroactive solution here.

Possible steps to reproduce:
1. (Optional) I spun up a quick docker container with `docker run -it --rm --entrypoint /usr/bin/bash node:latest`
2. Initialize an Angular 17 project with `npx @angular/cli@17 new`
3. Get into project directory
4. Try to add Angular Three with `npx ng add angular-three`
5. Accept prompt to install proposed version
6. Observe error

```
root@8977b934e1c1:/test# npx ng add angular-three
ℹ Using package manager: npm
⚠ Unable to find compatible package. Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package angular-three@2.5.1 will be installed and executed.
Would you like to proceed? Yes
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: test@0.0.0
npm error Found: @angular/common@17.3.12
npm error node_modules/@angular/common
npm error   @angular/common@"^17.3.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@">=18.0.0 <19.0.0" from angular-three@2.5.1
npm error node_modules/angular-three
npm error   angular-three@"2.5.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /root/.npm/_logs/2024-10-11T15_35_53_581Z-eresolve-report.txt
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-11T15_35_53_581Z-debug-0.log
✖ Packages installation failed, see above.
```

**Comment by AadamZ5** [comment]
Just read the v2 release issue #35, seems like Angular 18 might be a hard requirement with no `peerDependencies`-friendly solution in place for Angular 17, which is understandable after a large refactor. 

Hope a compatibility matrix is available soon, and if this particular Angular 17 issue can't be resolved, I'll look forward to when we upgrade to Angular 18 :)

**Comment by nartc** [comment]
@AadamZ5 hey, thanks for raising the issue. 

Yes, this is a hard requirement that I have to make for v2 because of how Angular Signals and Change Detection work in Angular 18. 

If you want to, `npm i --force` would work but you'd have to pay extra attention to how events/signals work in Angular Three code and to me, that's a lot of extra mental overhead to think about. 

That said, I won't be able to adjust the `peerDependencies` to support v17+ unfortunately. I'll close the issue. Sorry for the inconvenience.
