### ISSUE TITLE
About EffectComposer

### ISSUE THREAD

**Issue by yywf77** [angular-threejs/angular-three#60]
Hi nartc
When using EffectComposer an error message will be displayed during runtime. What should I do to solve this problem？

[.WebGL-0x110053dc700] GL_INVALID_VALUE: Texture dimensions must all be greater than zero.
[.WebGL-0x110053dc700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.

**Comment by nartc** [comment]
Can you share a reproduce repo for this?

**Comment by yywf77** [comment]
I'm very sorry, the speed of accessing GitHub in China is too slow. It took me a whole morning, but I couldn't upload it！

as below，I tried putting the effect in afterNextRender to solve the problem。

        afterNextRender(()=>{
            const [camera,enable,composer] = [this.camera,this.enable(),this.composer()];

            effect((onCleanup)=>{
                composer.addPass(new EffectPass(camera,this.effect()));
                onCleanup(()=>{
                    composer.removeAllPasses();
                });
            },{injector:this.injector});

            requestAnimationFrame(function render(){
                requestAnimationFrame(render);
                if(enable){
                    composer.render();
                }
            })；
        });

Another issue is that if I use injectBeforeRender instead of requestAnimationFrame, the effect won't work。
like this:
            injectBeforeRender(()=>{
                if(enable){
                    composer.render();
                }
            },{injector:this.injector});

**Comment by nartc** [comment]
What effect is this? Your custom effect?

**Comment by yywf77** [comment]
outline

**Comment by yywf77** [comment]
Hello nartc,
I tried to create a second view using Portals, but it always doesn't show up.

as below:

import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, viewChild } from "@angular/core";
import { extend, injectBeforeRender, NgtPortal, NgtPortalContent } from "angular-three";
import { NgtsOrthographicCamera } from 'angular-three-soba/cameras';
import * as THREE from "three";
extend(THREE);


@Component({
    selector: 'sm-loader-helper',
    standalone:true,
    template:`
        <ngt-portal [container]="secondaryScene">
            <ng-template portalContent>
                <ngts-perspective-camera [options]="{ makeDefault: true }" />
                <ngt-mesh>
                    <ngt-box-geometry />
                    <ngt-mesh-basic-material [color]="'mediumpurple'" />
                </ngt-mesh>
            </ng-template>
        </ngt-portal>
    `,
    imports: [NgtPortal, NgtPortalContent,NgtsOrthographicCamera],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoaderHelper{
    protected secondaryScene = new THREE.Scene();
    
    protected loader = viewChild<ElementRef<THREE.Mesh>>('loader');

    constructor(){
        injectBeforeRender(() => {
            const mesh = this.loader()?.nativeElement;
            if(mesh){
                mesh.rotation.x += 0.01;
                mesh.rotation.y += 0.01;
            }
        });
    }
}
