### ISSUE TITLE
Documentation - First Scene - Animation

### ISSUE THREAD

**Issue by qagwaai** [angular-threejs/angular-three#63]
scene-graph.component.ts in document - https://angularthree.netlify.app/core/getting-started/first-scene/#animation

Current
`import { Component, CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrategy } from '@angular/core';`

Suggested change
`import { Component, CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrategy, ElementRef, viewChild } from '@angular/core';`

**Comment by nartc** [comment]
Would you like to make a PR?

**Comment by qagwaai** [comment]
no worries - added [https://github.com/angular-threejs/angular-three/pull/65](https://github.com/angular-threejs/angular-three/pull/65) for review.
