### ISSUE TITLE
ngt-mesh scale not update when changing input state

### ISSUE THREAD

**Issue by Synone** [angular-threejs/angular-three#64]
Context: Following this tutorial for Angular Three Introduction: https://angular-threejs.netlify.app/docs/getting-started/first-scene.
When componentizing the cube, add properties: 
![image](https://github.com/user-attachments/assets/dc6fd336-ece1-4b3c-8c57-3fe2cfee650c)
Click and the cube does not change scale, I have to make 'active' into signal and set the value when clicking to see updates, or using ChangeDetectionStrategy OnPush, using changeDetectionRef to detectChanges() on click event. The same for hovered.

**Comment by nartc** [comment]
I need to take down that version of the doc. https://angularthree.org/core/getting-started/first-scene/ this is the correct doc that reflects the current state of this package.
