### ISSUE TITLE
spaces in git repo

### ISSUE THREAD

**Issue by qagwaai** [angular-threejs/angular-three#66]
```
apps/ionic-app/src/assets /shapes.svg
apps/ionic-app/src/assets /icon/favicon.png
```
for these two assets, there seems to be a space in the git path (shown above).  Unfortunately, this seems to give all sorts of trouble when cloning into a windows machine (and why there is no PR associated).  Seems to have been a commit about 5 months ago.  Is it possible to get these artifacts moved to a path without the space?

**Comment by nartc** [comment]
Thanks for reporting. Not sure how it happened (I used the ionic CLI, or the community Nx Ionic plugin to generate the app)
